--- Kernel/drivers/gpu/pvr/Makefile
+++ Kernel/drivers/gpu/pvr/Makefile
@@ -23,27 +23,20 @@
 	-DSUPPORT_SGX_HWPERF \
 	-DSYS_USING_INTERRUPTS \
 	-DPVR_SECURE_HANDLES \
-	-DSERVICES4 \
-	-DSUPPORT_SGX_EVENT_OBJECT \
 	-DTRANSFER_QUEUE \
 	-DSUPPORT_SGX \
-	-DSUPPORT_SRVINIT \
 	-DSUPPORT_HW_RECOVERY \
-	-DPVR_SECURE_FD_EXPORT \
-	-DSUPPORT_SGX_EVENT_OBJECT \
 	-DLDM_PLATFORM \
-	-DPVR2D_ALT_2DHW \
 	-DPVR_LINUX_USING_WORKQUEUES \
 	-DPVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE \
 	-DPVR_LINUX_TIMERS_USING_WORKQUEUES \
 	-DSYS_CUSTOM_POWERLOCK_WRAP \
 	-DSUPPORT_MEMINFO_IDS \
 	-DSYS_SGX_ACTIVE_POWER_LATENCY_MS=100 \
-	-DPVR_BUILD_DATE="" \
 	-DPVRSRV_MODNAME="\"pvrsrvkm\"" \
 	-Idrivers/gpu/pvr/sgx \
-	-DPVRSRV_RESET_ON_HWTIMEOUT \
- 	-DPVRSRV_DEBUG_OS_MEMORY
+	-DSUPPORT_GET_DC_BUFFERS_SYS_PHYADDRS \
+	-DPVR_LDM_DRIVER_REGISTRATION_NAME="\"pvrsrvkm\""
 
 ccflags-$(CONFIG_PVR_BUILD_RELEASE) += \
 	-DPVR_BUILD_TYPE="\"release\"" -DRELEASE
@@ -70,7 +63,7 @@
 ccflags-$(CONFIG_PVR_DUMP_MK_TRACE) += -DPVRSRV_DUMP_MK_TRACE
 
 ccflags-$(CONFIG_PVR_PDUMP) += \
-	-DPDUMP -DSUPPORT_DBGDRV_EVENT_OBJECTS -DSUPPORT_PDUMP_MULTI_PROCESS
+	-DPDUMP -DSUPPORT_PDUMP_MULTI_PROCESS
 
 pvrsrvkm-y := \
 	osfunc.o \
@@ -102,6 +95,7 @@
 	bridged_pvr_bridge.o \
 	perproc.o \
 	lists.o \
+	refcount.o \
 	sgx/bridged_sgx_bridge.o \
 	sgx/sgxinit.o \
 	sgx/sgxpower.o \
@@ -110,8 +104,7 @@
 	sgx/sgxkick.o \
 	sgx/sgxtransfer.o \
 	sgx/mmu.o \
-	sgx/pb.o \
-	mem_debug.o
+	sgx/pb.o
 
 ccflags-$(CONFIG_ARCH_S5PV210) += \
 	-DPVR_BUILD_DIR="\"smdkc110_android\"" \
@@ -131,13 +124,8 @@
 	s3c_lcd/s3c_displayclass.o \
 	s3c_lcd/s3c_lcd.o
 
-s3c_bc-y := \
-	s3c_bc/s3c_bc.o \
-	s3c_bc/s3c_bc_linux.o
-
-obj-$(CONFIG_PVR_PDUMP) += dbgdrv
+obj-$(CONFIG_PVR_PDUMP) += dbgdrv/
 
 obj-$(CONFIG_PVR_SGX) += pvrsrvkm.o
 
 obj-$(CONFIG_ARCH_S5PV210) += s3c_lcd.o
-obj-$(CONFIG_ARCH_S5PV210) += s3c_bc.o
